# Generated by Django 4.0.5 on 2022-07-18 18:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=40)),
                ('categoria_producto', models.CharField(max_length=40)),
                ('marca_producto', models.CharField(max_length=40)),
                ('descripcion_producto', ckeditor.fields.RichTextField()),
                ('precio', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('fecha_creacion_producto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_usuario', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=40)),
                ('apellido_nombre', models.CharField(max_length=80)),
                ('correo_elec', models.EmailField(max_length=90)),
                ('nro_celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('id_producto', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('valor_total', models.IntegerField()),
            ],
        ),
    ]
